import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Page/Header";
import HeaderMobile from "@/components/Page/HeaderMobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <HeaderMobile />
        {children}
      </body>
    </html>
  );
}
