import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Page/header/Header';
import HeaderMobile from '@/components/Page/header/HeaderMobile';
import Footer from '@/components/Page/footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header />
				<HeaderMobile />
				{children}
				<Footer />
			</body>
		</html>
	);
}
